### ISSUE TITLE
AttributeError: module 'modules' has no attribute 'spinOSGUI'

### ISSUE THREAD

**Issue by kluskaj** [matthiasfabry/spinOS#8] opened 2022-02-11 10:44 UTC
Hi Matthias,

I wanted to use your code again. 
However, after a `git pull`, I tried to run spinOS in the spinOS directory with:
`python spinOS.py .`

This the error I got:
![Screenshot 2022-02-11 at 11 43 30](https://user-images.githubusercontent.com/11367352/153577921-59f6c6d1-4cb8-4a29-9c4d-e35025fd0b62.png)

I checked in modules and spinOSGUI.py is there.
Any thoughts?

Thanks,
Cheers,
Jacques

**Comment by matthiasfabry** [comment] 2022-02-11 10:59
I have merged the develop branch into the master branch. Can you `pull` the master branch and try again?

**Comment by kluskaj** [comment] 2022-02-11 11:45
I run into a new error:
![Screenshot 2022-02-11 at 12 45 43](https://user-images.githubusercontent.com/11367352/153586034-dc52a01a-f59a-43c2-82e3-ec7676ad804d.png)

**Comment by matthiasfabry** [comment] 2022-02-11 12:20
Apparently, this is due to a circular `import`. 
I can reproduce this with python 3.6.

I've hotfixed the issue for 3.6, but I recommended to update to python >3.9, where this didn't happen at all.

**Comment by kluskaj** [comment] 2022-02-11 12:50
ok, I was fighting with it a bit. Could not run it with python3.6 still.
I tried to run it with python3.10.
It almost runs. After the logo appeared I got a new error though...
![Screenshot 2022-02-11 at 13 48 46](https://user-images.githubusercontent.com/11367352/153594163-b0355969-6d19-4892-9bc4-b37b1ed191aa.png)

PS: As a side suggestion, could you maybe associate a yml file to spinos so one can run it in the right environment straight away? :)
Cheers

**Comment by matthiasfabry** [comment] 2022-02-11 13:04
ok so it seems tkinter changes when going from 3.9 to 3.10. I added a yaml in the directory.

**Closed as completed** 2022-02-14 14:44 UTC
Labels: bug
